# **1. PyTorch Basic**
- Reference의 예제 코드에서 내용 선정 및 발췌 후 정리 및 수정, 보완함
- Reference
  - 파이토치 첫걸음(제이펍) 예제코드

## 1-1. 기본 모듈 임포트

In [ ]:
import numpy as np
import torch

## 1-2. GPU 설정하기

In [ ]:
# torch.cuda.is_available()를 통해 현재 시스템의 상태를 인식, 지정하면 GPU또는 CPU를 상황에 맞게 적용할 수 있다.
# device='cuda' 또는 device='cuda:0'와 같은 방법으로 직접 지정할 수 있다. (0: GPU의 Index)

USE_CUDA = torch.cuda.is_available()
DEVICE = torch.device("cuda" if USE_CUDA else "cpu")
print(DEVICE)

cpu


## 1-3. 기본 데이터형(텐서) 사용하기

In [ ]:
# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])
print(t)

# device를 지정하면 GPU로 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], device='cuda')
print(t)

# dtype을 사용해 데이터형을 지정해 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)
print(t)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
# 0부터 9까지의 수치로 초기화된 1차원 Tensor
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
#모든 값이 0인 100 x 10 의 Tensor를 작성해서 to메서드로 GPU에 전송
print(DEVICE)
if DEVICE == 'cuda':
  t = torch.zeros(100, 10).to("cuda:0")
  print(t)

else:
  t = torch.zeros(100, 10)
  print(t)

cuda
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
# 정규 난수로 100 x 10의 Tensor를 작성
t = torch.randn(100, 10)
print(t)

tensor([[-1.4195e+00, -2.0025e-01, -1.1715e+00,  4.1667e-01,  7.5366e-01,
          8.8096e-01,  3.7874e-01, -1.4792e+00, -3.0555e-01, -1.1306e-01],
        [ 3.9296e-01,  1.1997e+00, -7.7086e-01, -2.2586e-01,  2.0311e-02,
         -1.1573e+00,  5.8013e-01,  6.3500e-01,  7.8227e-01, -8.0026e-01],
        [-9.4905e-01,  7.2858e-01, -6.0517e-01, -3.3236e-01,  1.1671e+00,
         -3.7184e-01,  8.0309e-01,  6.3571e-01,  2.0980e-01,  1.3590e+00],
        [ 1.3655e+00, -1.2878e+00, -1.4510e+00, -1.3068e-01,  1.1176e+00,
         -1.3416e+00, -3.8814e-01,  1.4212e-01,  9.2935e-01, -1.1946e+00],
        [-1.3736e+00,  9.2787e-01, -1.5391e+00, -4.6300e-01,  3.9693e-01,
          1.6241e+00, -2.7523e-01,  1.7327e+00, -1.0144e+00, -9.6572e-01],
        [-1.1641e+00,  1.5359e+00,  8.5201e-01, -4.4431e-01, -1.0375e+00,
          1.3874e-01,  6.0440e-01, -1.0745e+00,  3.3639e-01,  1.4777e+00],
        [ 1.5404e+00, -1.9566e+00,  2.9051e-01,  7.6166e-01, -1.5169e+00,
          7.6626e-01,  4.4951e-0

In [ ]:
# Tensor의 shape은 size 메서드로 취득 가능
t.size()

torch.Size([100, 10])

In [ ]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1, 2], [3, 4.]])
t

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
x = t.numpy()
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
# GPU上상의 Tensor는 cpu메서드로,
# CPU의 Tensor로 이동(변환)할 필요가 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")
x = t.to("cpu").numpy()
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
t = torch.tensor([[1,2,3], [4,5,6.]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# 스칼라 첨자 지정
print(t[0, 2])

# 슬라이스로 지정
print(t[:, :2])

# 리스트로 지정
print(t[:, [1,2]])

# 마스크 배열을 시용해서 3보다 큰 부분만 선택
print(t[t > 3])

tensor(3.)
tensor([[1., 2.],
        [4., 5.]])
tensor([[2., 3.],
        [5., 6.]])
tensor([4., 5., 6.])


In [ ]:
# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100
print(t)

# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200
print(t)      

# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])
tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


In [ ]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
print('v=', v)
print('w=', w)
print('----------------------------------------------')

v= tensor([1., 2., 3.])
w= tensor([ 0., 10., 20.])
----------------------------------------------


In [ ]:
# 2 × 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])
print('m=', m)
print('----------------------------------------------')

m= tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])
----------------------------------------------


In [ ]:
# 벡터와 스칼라의 덧셈
v2 = v + 10
print('v2=', v2)

v2= tensor([11., 12., 13.])


In [ ]:
# 자승도 같은 방식
v2 = v ** 2
print('v2=', v2)

v2= tensor([1., 4., 9.])


In [ ]:
# 동일 길이의 벡터 간 뺄쎔
z = v - w
print('z=', z)

z= tensor([  1.,  -8., -17.])


In [ ]:
# 여러 가지 조합
u = 2 * v - w / 10 + 6.0
print('u=', u)
print('----------------------------------------------')

u= tensor([ 8.,  9., 10.])
----------------------------------------------


In [ ]:
# 행렬과 스칼라
m2 = m * 2.0
print('m2=', m2)

m2= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [ ]:
# 행렬과 벡터
#(2, 3)인 행렬과 (3,)인 벡터이므로 브로드 캐스트가 작동
m3 = m + v
print('m3=', m3)
# 행렬 간 처리
m4 = m + m
print('m4=', m4)
print('----------------------------------------------')


m3= tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
m4= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
----------------------------------------------


In [ ]:
# 100 × 10의 테스트 데이터 생성
X = torch.randn(100, 10)
print(X)
print("X=", X)
print('----------------------------------------------')

# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)
print("y=", y)
print('----------------------------------------------')

# 평균치 구하기
m = torch.mean(X)
print('m=', m)
print('----------------------------------------------')

# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()
print('m=', m)
print('----------------------------------------------')

# 집계 결과는 0차원의 Tensor로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
print('m_value=', m_value)
print('----------------------------------------------')

# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서,
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)
print('m2=', m2)
print('----------------------------------------------')

tensor([[ 7.2740e-01, -3.8103e-01,  1.2323e+00, -1.1125e+00,  2.1223e+00,
         -1.3010e-01,  6.7068e-01, -1.3980e+00, -1.0099e+00,  1.0266e+00],
        [-9.5045e-01, -8.8284e-01, -5.7023e-01, -1.9411e-01, -1.0194e+00,
          1.3391e+00,  2.4549e-01,  1.2038e+00, -1.9821e+00,  1.5756e+00],
        [ 7.2997e-01, -1.4685e+00,  1.1435e+00,  3.0743e-02,  1.5007e-01,
         -3.2701e-01,  8.8925e-01, -6.1868e-01,  8.1744e-01, -8.9386e-01],
        [-1.6616e-01,  2.6470e-01, -5.7589e-01, -9.3633e-02,  2.0412e-01,
          4.8116e-01,  1.3502e+00,  1.4168e-02, -5.8506e-01,  8.3771e-02],
        [-1.5080e+00,  8.5749e-01,  3.5203e-01,  2.0523e-02,  7.1616e-02,
          8.6854e-01, -7.5782e-01, -3.3792e-01, -1.2370e-01,  1.1776e-01],
        [-1.0945e+00,  1.5161e+00,  4.7950e-01,  1.1408e+00, -4.9308e-01,
         -8.8945e-01,  2.6782e-01,  1.2887e-02,  2.6184e-01, -1.8108e-01],
        [ 9.6294e-01,  8.5145e-01,  6.1148e-02,  1.3839e+00, -3.1436e-01,
         -3.6988e-02,  1.0890e+0

In [ ]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2×2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2×3

# 2×2를 4×1로 보여준다
print(x1)
print(x1.view(4, 1))
print('----------------------------------------------')
print(x1)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
----------------------------------------------
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# -1는 나머지 차원을 나타내며 한 번만 사용할 수 있다
# 아래 예에선 -1을 사용하면 자동으로 4가 된다
print(x1.view(1, -1))
print('----------------------------------------------')

tensor([[1., 2., 3., 4.]])
----------------------------------------------


In [ ]:
# 2×3을 전치해서 3×2로 만든다
print(x2.t())
print('----------------------------------------------')
print(x2)
x3 = x2.t()
print(x3)

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])
----------------------------------------------
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])


In [ ]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2×2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2×3
print(x1)
print(x2)
# dim=1로 결합하면 2×5의 Tensor를 만든다
torch.cat([x1, x2], dim=1)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])


tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [ ]:
# HWC을 CHW로 변환
# 64×32×3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
print(hwc_img_data)
print('----------------------------------------------')
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(chw_img_data)

tensor([[[[9.4037e-03, 4.8588e-01, 4.5828e-01],
          [5.9016e-01, 2.9783e-01, 2.8714e-02],
          [9.7874e-01, 4.7107e-01, 7.0266e-01],
          ...,
          [4.3467e-01, 8.7103e-02, 3.1253e-01],
          [1.6004e-01, 9.4945e-01, 8.9571e-02],
          [4.3911e-01, 6.9080e-01, 2.1348e-01]],

         [[7.2684e-02, 5.2021e-01, 7.3438e-01],
          [9.9310e-01, 6.6968e-01, 6.1334e-01],
          [7.4088e-01, 8.9706e-01, 6.6683e-01],
          ...,
          [8.9917e-01, 1.1843e-03, 8.8767e-01],
          [8.3972e-01, 3.9703e-03, 2.4527e-01],
          [6.8039e-01, 7.8045e-01, 2.3722e-02]],

         [[8.3424e-01, 8.0084e-01, 7.0352e-01],
          [8.8842e-01, 9.4678e-01, 4.8998e-01],
          [5.3277e-02, 2.6866e-01, 7.6510e-01],
          ...,
          [1.7446e-01, 3.8352e-02, 3.4034e-01],
          [6.4243e-01, 1.5077e-01, 6.7222e-01],
          [3.0414e-01, 7.9845e-01, 6.5133e-01]],

         ...,

         [[8.1001e-01, 6.1591e-02, 4.9190e-01],
          [9.7682e-01,

In [ ]:
m = torch.randn(100, 10)
v = torch.randn(10)
print('m = ', m)
print('v = ', v)

# 내적
d = torch.dot(v, v)
print('d = v·v = ', d)
print('----------------------------------------------')

# 100 × 10의 행렬과 길이 10인 벡터의 곱
# 결과는 길이 100인 벡터
v2 = torch.mv(m, v)
print('v2 = ', v2)
print('----------------------------------------------')

# 행렬곱
m2 = torch.mm(m.t(), m)
print('m2 = ', m2)
print('----------------------------------------------')

m =  tensor([[-5.1751e-01,  5.8291e-01, -1.3851e+00, -6.4811e-01,  2.2874e-01,
          6.8807e-01,  9.4572e-01, -6.7479e-02,  8.4515e-02,  7.5731e-03],
        [-5.4957e-01,  1.1388e+00, -1.5599e-01,  9.0865e-01,  1.2391e-01,
          5.1055e-01, -2.9956e-01, -2.7950e-01, -3.5384e-01,  2.2977e-01],
        [ 9.6186e-01,  1.3715e+00,  1.9492e+00,  4.6118e-01,  1.6293e+00,
         -4.2877e-01,  1.1168e+00, -9.8162e-01,  1.0179e+00, -5.2730e-02],
        [ 1.3237e+00, -6.4393e-01, -7.8141e-01,  3.7752e-01,  8.4745e-02,
         -1.4922e+00, -1.9308e+00, -1.0159e+00, -1.2076e+00,  1.1497e+00],
        [ 7.8296e-01, -8.3170e-01,  1.0641e+00,  3.6119e-01,  3.7039e-01,
          7.0332e-01,  6.8750e-01,  1.8098e+00, -1.2578e-01,  5.8351e-02],
        [-1.3121e+00,  3.7282e-01, -2.2120e-01, -1.0969e+00, -2.2872e+00,
         -4.5882e-01,  1.4538e+00, -1.6827e-01,  1.9587e+00,  1.1919e-02],
        [-1.3721e-01, -9.9713e-01,  6.2520e-01,  7.9531e-01,  1.4136e-01,
         -6.4131e-01,  4.66

In [ ]:
# 특이값 분해
u, s, v = torch.svd(m)
print('u = ', u)
print('s = ', s)
print('v = ', v)

u =  tensor([[-3.4348e-02,  1.0443e-01, -8.7386e-02, -3.6236e-02,  1.1175e-01,
         -2.1954e-02,  2.9234e-02, -5.5564e-02,  2.5614e-03, -4.7139e-02],
        [ 8.3911e-02,  3.6263e-02, -6.3944e-02, -3.9781e-02,  1.9588e-02,
         -2.4081e-02,  8.3105e-03,  1.1129e-01,  2.4327e-02,  4.6190e-02],
        [ 4.8622e-02,  6.2734e-02,  4.0197e-02, -4.7514e-02, -2.4536e-01,
         -1.2350e-01,  1.5847e-01,  6.1440e-02, -7.3548e-03, -2.1635e-01],
        [ 3.4718e-02, -2.5330e-01,  1.0348e-02, -3.4777e-02,  5.8962e-02,
         -1.3735e-01,  2.3448e-02, -4.1321e-03, -1.3081e-01,  1.2937e-01],
        [ 5.3765e-02,  4.1707e-02,  8.3814e-02,  1.1802e-01, -4.7102e-02,
          1.0504e-01, -8.5107e-02, -4.7977e-02, -1.2311e-01, -1.4947e-01],
        [-1.9391e-01,  1.5811e-01,  6.8772e-02, -1.1488e-01,  1.5381e-02,
          1.2045e-01,  6.4263e-02,  4.4935e-02,  6.3872e-02,  1.4053e-01],
        [-5.4568e-02, -7.5847e-02, -5.9215e-02,  1.5185e-01, -9.2636e-02,
         -1.8172e-02,  5.56

In [ ]:
x = torch.randn(100, 3)
print('x = ', x)
print('----------------------------------------------')

# 미분의 변수로 사용하는 경우는 requires_grad를 True로 설정
a = torch.tensor([1, 2, 3.], requires_grad=True)
print('a = ', a)
print('----------------------------------------------')

# 계산을 통해 자동으로 계산 그래프가 구축된다
y = torch.mv(x, a)
o = y.sum()
print('o = ', o)
print('----------------------------------------------')

# 미분을 실행
o.backward()

# 분석 답과 비교
a.grad != x.sum(0)

x =  tensor([[ 1.0667, -1.0013,  0.0738],
        [-0.6318, -0.8667, -0.6509],
        [-0.7167,  1.2600, -2.7644],
        [ 0.2296, -0.7181,  0.5501],
        [ 0.2051,  0.2832, -0.7307],
        [-0.5113,  1.0470, -0.1530],
        [ 0.2402,  0.0606, -0.7700],
        [-0.2238,  0.1013,  0.7168],
        [ 1.9356,  0.7970, -0.9310],
        [ 0.0705,  0.1762, -0.0532],
        [ 0.9764,  1.6867,  0.8483],
        [ 0.0727,  0.7047, -0.5898],
        [-0.9593,  0.3356,  2.3132],
        [ 1.2505, -1.8178,  1.1332],
        [ 1.6168,  0.6804, -1.9254],
        [-0.4781,  1.0307, -0.8953],
        [-1.5940, -1.0399,  0.3399],
        [ 0.7149, -1.8120,  1.4617],
        [-0.6119,  0.0992, -1.6334],
        [ 1.1427,  1.2676,  0.2663],
        [-0.1449, -0.2606,  0.7884],
        [ 0.7484,  1.3881, -1.2272],
        [-0.2550,  0.5097,  0.8220],
        [-1.1844,  0.8233,  0.3923],
        [ 0.3465,  1.3608,  0.2105],
        [-0.7072, -0.9193,  1.1727],
        [-0.1958,  0.8683,  0.467

tensor([True, True, True])

In [ ]:
# x는 requires_grad가 False이므로 미분이 계산되지 않는다
x.grad is None

True